os: Visual Studio 2015

environment:
  matrix:

### MSVC Toolchains ###

  # Ruby 2.4

  # Stable 64-bit MSVC
    - channel: 1.25.0
      target: x86_64-pc-windows-msvc
      platform: x64
      RUBY_VERSION: 24
      RUST_BACKTRACE: full
  # Stable 32-bit MSVC
    - channel: 1.25.0
      target: i686-pc-windows-msvc
      platform: x86
      RUBY_VERSION: 24
      RUST_BACKTRACE: full
#  # Beta 64-bit MSVC
#    - channel: beta
#      target: x86_64-pc-windows-msvc
#      platform: x64
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#  # Beta 32-bit MSVC
#    - channel: beta
#      target: i686-pc-windows-msvc
#      platform: x86
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#  # Nightly 64-bit MSVC
#    - channel: nightly
#      target: x86_64-pc-windows-msvc
#      platform: x64
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"
#  # Nightly 32-bit MSVC
#    - channel: nightly
#      target: i686-pc-windows-msvc
#      platform: x86
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"

  # Ruby 2.5

  # Stable 64-bit MSVC
    - channel: 1.25.0
      target: x86_64-pc-windows-msvc
      platform: x64
      RUBY_VERSION: 25
      RUST_BACKTRACE: full
  # Stable 32-bit MSVC
    - channel: 1.25.0
      target: i686-pc-windows-msvc
      platform: x86
      RUBY_VERSION: 25
      RUST_BACKTRACE: full
#  # Beta 64-bit MSVC
#    - channel: beta
#      target: x86_64-pc-windows-msvc
#      platform: x64
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#  # Beta 32-bit MSVC
#    - channel: beta
#      target: i686-pc-windows-msvc
#      platform: x86
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#  # Nightly 64-bit MSVC
#    - channel: nightly
#      target: x86_64-pc-windows-msvc
#      platform: x64
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"
#  # Nightly 32-bit MSVC
#    - channel: nightly
#      target: i686-pc-windows-msvc
#      platform: x86
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"
#
### GNU Toolchains ###

  # Ruby 2.4

  # Stable 64-bit GNU
    - channel: 1.25.0
      target: x86_64-pc-windows-gnu
      platform: x64
      RUBY_VERSION: 24
      RUST_BACKTRACE: full
  # Stable 32-bit GNU
    - channel: 1.25.0
      target: i686-pc-windows-gnu
      platform: x86
      RUBY_VERSION: 24
      RUST_BACKTRACE: full
#  # Beta 64-bit GNU
#    - channel: beta
#      target: x86_64-pc-windows-gnu
#      platform: x64
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#  # Beta 32-bit GNU
#    - channel: beta
#      target: i686-pc-windows-gnu
#      platform: x86
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#  # Nightly 64-bit GNU
#    - channel: nightly
#      target: x86_64-pc-windows-gnu
#      platform: x64
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"
#  # Nightly 32-bit GNU
#    - channel: nightly
#      target: i686-pc-windows-gnu
#      platform: x86
#      RUBY_VERSION: 24
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"

  # Ruby 2.5

  # Stable 64-bit GNU
    - channel: 1.25.0
      target: x86_64-pc-windows-gnu
      platform: x64
      RUBY_VERSION: 25
      RUST_BACKTRACE: full
  # Stable 32-bit GNU
    - channel: 1.25.0
      target: i686-pc-windows-gnu
      platform: x86
      RUBY_VERSION: 25
      RUST_BACKTRACE: full
#  # Beta 64-bit GNU
#    - channel: beta
#      target: x86_64-pc-windows-gnu
#      platform: x64
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#  # Beta 32-bit GNU
#    - channel: beta
#      target: i686-pc-windows-gnu
#      platform: x86
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#  # Nightly 64-bit GNU
#    - channel: nightly
#      target: x86_64-pc-windows-gnu
#      platform: x64
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"
#  # Nightly 32-bit GNU
#    - channel: nightly
#      target: i686-pc-windows-gnu
#      platform: x86
#      RUBY_VERSION: 25
#      RUST_BACKTRACE: full
#      #cargoflags: --features "unstable"

matrix:
  allow_failures:
    - channel: nightly

install:
  - ps: |
        $env:PATH += ";C:\rust\bin";
        if ($env:platform -eq 'x86') {
          $env:RUBY_DIR = "Ruby${env:RUBY_VERSION}"
          $arch_expanded = "i686-pc-windows-${env:BUILD_TARGET}";
          $env:ARCH = "x86";
          $env:bits = "32";
        } else {
          $env:RUBY_DIR = "Ruby${env:RUBY_VERSION}-x64"
          $arch_expanded = "x86_64-pc-windows-${env:BUILD_TARGET}";
          $env:ARCH = "amd64";
          $env:bits ="64";
        }
        $env:WIN_RUBY_BIN = "C:\${env:RUBY_DIR}\bin";
        $env:PATH = "${env:WIN_RUBY_BIN};${env:PATH}";
        if ($env:BUILD_TARGET -eq 'gnu') {
          $env:PATH += ";C:\msys64\mingw${env:bits}\bin";
          gcc --version;
        }
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - ruby --version
  - gem -v
  - bundle -v

build: false

test_script:
  - cargo test -vv

cache:
  - '%USERPROFILE%\.cargo'
  - '%USERPROFILE%\.rustup\downloads'
  - C:\Users\appveyor\.cargo\registry
  - target
