source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in rutie_ruby_gvl_example.gemspec
gemspec
group :test do
  gem 'minitest', '~> 5.10'
  gem 'minitest-reporters', '~> 1.1'
  gem 'color_pound_spec_reporter', '~> 0.0.6'
end

