[package]
name = "rutie_ruby_example"
version = "0.1.0"
authors = ["Daniel P. Clark <6ftdan@gmail.com>"]
edition = "2021"

[dependencies]
rutie = { path = "../../" }

[lib]
name = "rutie_ruby_example"
crate-type = ["dylib"]
