# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in rutie_ruby_example.gemspec
gemspec

# Not needed for production code. Gemspec file is enough for your gems.
gem 'rutie', path: '../../gem/'

group :test do
  gem 'color_pound_spec_reporter', '~> 0.0.6'
  gem 'minitest', '~> 5.10'
  gem 'minitest-reporters', '~> 1.1'
end
