require "bundler/gem_tasks"
require "rake/testtask"

desc 'Build Rust extension'
task :build_lib do
  sh 'cargo build --release'
end

Rake::TestTask.new(test: :build_lib) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task :default => :test
