---
name: CI

# on:
#   push:
#     branches:
#       - master
#
#   pull_request:

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        ruby: ["2.7", "3.0", "3.1", "head"]
        rust: ["stable", "beta"]
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rustup-toolchain: ${{ matrix.rust }}
          bundler-cache: true
          cargo-cache: true

      - name: Lint rust
        run: cargo clippy && cargo fmt --check
      
      - name: Run rust doc tests
        run: cargo test --doc

      - name: Run ruby tests
        run: | 
          git submodule update --init
          cd ../gem
          rake test
